const path = {
  home: '/',
  newFeed: '/news',
  project: '/project',
  newsDetail: '/news/:newId',
  createProject: '/createProject',
  myProject: '/myProject',
  login: '/login',
  register: '/register',
  profile: '/profile',
  projectManagement: 'projectManagement',
  inbox: 'inbox',
  timeLine: 'timeLine',
  calendarMentor: 'calendarMentor',
  calendarLecturer: 'calendarLecturer',
  financialReport: 'financialReport',
  projectDetail: 'projectManagement/:projectId',
  all_management: '/manage',
  manager_event_management: 'event',
  manager_approval_management: 'approval',
  mentor_schedule_management: 'schedule',
  admin_account_management: 'accounts',
  admin_semester_course: 'semester-course',
  admin: '/admin',
  taskManagement: 'taskManagement',
  projectTaskDetail: ':projectTaskId',
  profile_skills: 'skills',
};
export default path;
