const path = {
  home: '/',
  newFeed: '/news',
  project: '/project',
  newsDetail: '/news/:newId',
  createProject: '/createProject',
  myProject: '/myProject',
  login: '/login',
  register: '/register',
  profile: '/profile',
  projectManagement: 'projectManagement',
  timeLine: 'timeLine',
  calendarMentor: 'calendarMentor',
  financialReport: 'financialReport',
  projectDetail: 'projectManagement/:projectId',
  manager_project_management: '/manager',
  manager_event_management: 'event',
  manager_approval_management: 'approval',
  mentor_project_management: '/mentor',
  mentor_schedule_management: 'schedule',
  admin_account_management: '/admin',
  admin_dashboard: 'dashboard',
  taskManagement: 'taskManagement',
  projectTaskDetail: ':projectTaskId',
};
export default path;
